### ISSUE TITLE
Animated gifs on SlideFragment

### ISSUE THREAD

**Issue by alexmantaut** [TangoAgency/material-intro-screen#107]
Is there a way to show animated GIFs using the basic Slide Fragment? (without having to create a custom slide)
Otherwise, I was thinking on maybe adding that functionality on Slide Fragment myself... what would be the best to do it?
I was thinking of modifying SlideFragment to add a different type of image called gifImage or (something like that) and creating an specific view for gifs as described here:
http://www.mavengang.com/2016/05/02/gif-animation-android/ and then adding

Any thoughts on the issue are welcome. Thanks

**Comment by radzio** [comment]
@alexmantaut  there is no ready-to-use API for this. However, you can create [CustomSlide ](https://github.com/TangoAgency/material-intro-screen/blob/master/app/src/main/java/agency/tango/materialintro/CustomSlide.java) and play gif there.

**Comment by alexmantaut** [comment]
That is ok, I'll use a CustomSlide then.
