### ISSUE TITLE
Version 0.0.5 not Gradle syncing

### ISSUE THREAD

**Issue by therealccarter** [TangoAgency/material-intro-screen#113]
Is this a known issue?

**Comment by radzio** [comment]
Do you have` jcenter()` maven repo in your `build.gradle` file? It is not a know issue - it is impossible no to work.

**Comment by therealccarter** [comment]
I've got this:

    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }

Is that not quite right?

I'm basing that off of this page: https://android-arsenal.com/details/1/4368#!package

and added "jecenter()" to it.

**Comment by therealccarter** [comment]
OK, got it to compile. The problem was that I was copying the compile line from that package tab on Android Authority, it has this:

    compile 'com.github.TangoAgency:material-intro-screen:0.0.5'

Which is not what I should have been adding.

**Comment by radzio** [comment]
@therealccarter  you should use this:

`compile 'agency.tango.android:material-intro-screen:0.0.5'`

We are not using jitpack in this project.

Check this out:
https://bintray.com/tangoagency/maven/material-intro-screen/0.0.5
