### ISSUE TITLE
Lag While Swiping

### ISSUE THREAD

**Issue by emanf** [TangoAgency/material-intro-screen#125]
when i use too many slides(like 12 slides or more) i experience lag. any idea how to fix it?

**Comment by KevCel** [comment]
I had the same problem. You should decrease size of images. For each images I have two copy: larger for tablets and smaller for smartphones.

**Comment by emanf** [comment]
I'm using small images like icons for my intro activity, can it be still the problem?

**Comment by emanf** [comment]
i just test it with no image! still i have the same problem.

can someone help me? :(

**Comment by polvallsortiz** [comment]
Why it has been closed? I'm having the same issue...
