### ISSUE TITLE
Implement library only on first launch

### ISSUE THREAD

**Issue by Kvaibhav01** [TangoAgency/material-intro-screen#127]
Hey there! The library works great. I'm thinking what will I need to make the **intro run only the first time a user opens the app**. Any code for that?

**Comment by bezmian** [comment]
Issue not related to the library, but look at this, maybe this will help you.
https://stackoverflow.com/questions/15061653/run-a-piece-of-code-only-once-when-an-application-is-installed

**Comment by Kvaibhav01** [comment]
I implemented the code given there but there seems to be no effect on my app. 😞 Can you provide me some steps to do that? I'm really new to Android programming.
