### ISSUE TITLE
handle next/finish button click

### ISSUE THREAD

**Issue by abroresonaliev** [TangoAgency/material-intro-screen#129]
how I can handle next/finish button click. When next/finish button clicked on last slide I want call message button on click

**Comment by bezmian** [comment]
Override method onFinish in your IntroActivity class like here 
https://github.com/TangoAgency/material-intro-screen/blob/develop/app/src/main/java/agency/tango/materialintro/IntroActivity.java
![image](https://user-images.githubusercontent.com/17637583/32225218-a725df94-be44-11e7-94fe-f6b668011799.png)
