### ISSUE TITLE
How to add custom images for intro? From where should I get?

### ISSUE THREAD

**Issue by Kvaibhav01** [TangoAgency/material-intro-screen#130]
Hi there, I want to add material images (like that in Google apps) in my intro slides. 

1. **How should I add my own images** instead of the default `ic_next`? Because even if I add images from Image Asset to drawable folder and call it in `.image()` method it says _cannot resolve symbol ..._

2. **Is there any online editing tool or library of images** where I can get my custom material images?

**Comment by rdunlocked18** [comment]
Remove "agency.tango.materialintroscreen." this much part and give your File name
