### ISSUE TITLE
Next Slide Programmaticaly

### ISSUE THREAD

**Issue by valterh4ck3r** [TangoAgency/material-intro-screen#134]
I need to move to the next slide programmatically, it's possible ?

**Comment by anubhavmalik** [comment]
+1

**Comment by attanasio94g** [comment]
+1

**Comment by damionx7** [comment]
+1

**Comment by zboing** [comment]
In MaterialIntroActivity from the library you create the method:

    public void goToNextSlide() {
        viewPager.setCurrentItem(viewPager.getCurrentItem()+1, true);
    }

and in your activity project:

      addSlide(new SlideFragmentBuilder()
                        .backgroundColor(R.color.third_slide_background)
                        .buttonsColor(R.color.third_slide_buttons)
                        .image(R.drawable.img)
                        .title("title")
                        .description("description")
                        .build(),
                new MessageButtonBehaviour(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        goToNextSlide();
                    }
                }, "Button name"));
