### ISSUE TITLE
will it detect automatically first time app is launch to show into, and never show again?

### ISSUE THREAD

**Issue by Photogad** [TangoAgency/material-intro-screen#147]
I am not an android programmer but I'm the CEO of an app company and my developer died. I need to quickly put a material intro into one of my app. I don't really know java that well but I can follow the directions on the page. But my question is, if I add this library and the fragment, will this automatically detect the app is first opened by user and show the intro? And then never show it again after they complete the intro?

if not can anyone guide me how to do this. thank you very much for your help.

**Comment by radzio** [comment]
Hello, my condolences. This library does not have this functionality. You have to implement it on your own. You can use this: https://github.com/jonfinerty/Once to implement what you want.
