### ISSUE TITLE
not ok with android support appcompat v7:26.1.0

### ISSUE THREAD

**Issue by ThitSarNL** [TangoAgency/material-intro-screen#149]
Dear TangoAgency,
Your material-intro-screen has error with 
dependencies {
...
    implementation 'com.android.support:appcompat-v7:26.1.0'
...}
please, kindly fix it

**Comment by radzio** [comment]
@ThitSarNL  What errors :)?

**Comment by ThitSarNL** [comment]
<img width="1327" alt="screen shot 2018-02-26 at 7 40 59 pm" src="https://user-images.githubusercontent.com/34516413/36672478-c99cfd82-1b2d-11e8-947b-0718501a2f8f.png">
<img width="1141" alt="screen shot 2018-02-26 at 7 47 23 pm" src="https://user-images.githubusercontent.com/34516413/36672524-ecad269e-1b2d-11e8-92cf-93e8dd18f018.png">
<img width="748" alt="screen shot 2018-02-26 at 7 49 08 pm" src="https://user-images.githubusercontent.com/34516413/36672579-2a9e06f8-1b2e-11e8-9620-1ec53c0dc93a.png">

error is with sdk version 26 and not with version 27

**Comment by bezmian** [comment]
It isn't related to our library. 
![image](https://user-images.githubusercontent.com/17637583/36672659-6c706856-1b00-11e8-9974-68f648805e95.png)
![image](https://user-images.githubusercontent.com/17637583/36672670-72eee022-1b00-11e8-87c2-799703fdccdb.png)
As you can see we use 25.0.1 version of the Android Support Libraries.
You can check Gradle dependencies with  a 
```gradle app:dependencies```
 command in terminal to check what collides there

**Comment by RodrigoSolanoMarques** [comment]
To run I added the following
```
implementation 'com.android.support:appcompat-v7:27.1.0'
implementation 'com.android.support:design:27.1.0'
```
