### ISSUE TITLE
fixed checkbox style when try to customize it

### ISSUE THREAD

**Issue by MinaSamirCap** [TangoAgency/material-intro-screen#151]
I want to change the checked color of the checkbox using styles like this

`<android.support.v7.widget.AppCompatCheckBox
        android:id="@+id/checkbox"
        style="@style/CheckboxTheme"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/privacy_validation"
        android:textColor="@color/primary_text"
        android:textSize="20sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />`

it the checked color not changed ..

**Comment by bezmian** [comment]
Sorry, but issue is not related to the library.

**Comment by MinaSamirCap** [comment]
okay thanks ..
