### ISSUE TITLE
Failed to resolve in "app" gradle

### ISSUE THREAD

**Issue by gsb216200** [TangoAgency/material-intro-screen#154]
I keep gettings failed to resolve: agency.tango.andriod.material-intro-screen:26.1.0

In the intro activity java file I have a gazzilion errors with R. addslide, getbackbuttontrasnlationwrapper etc?

**Comment by radzio** [comment]
https://bintray.com/tangoagency/maven/material-intro-screen/0.0.5

![image](https://user-images.githubusercontent.com/469111/38211396-9c753042-36ba-11e8-8335-f08527146c6c.png)
