### ISSUE TITLE
add more padding around text in intro slides

### ISSUE THREAD

**Issue by Photogad** [TangoAgency/material-intro-screen#159]
I know you don't maintain or update this library anymore, but just throwing this out there.

it would be nice if you could change it so the text on the slides have more padding.  currently, the text pretty much touches the edges of the device and it looks bad.

it's sad this library isn't updated anymore because it's probably one of the best and easiest to use intro screen libraries out there for android.

**Comment by bezmian** [comment]
Hi @photog0411! You can always create a custom slide with custom padding :)
