### ISSUE TITLE
add the library to my project

### ISSUE THREAD

**Issue by rulogas** [TangoAgency/material-intro-screen#179]
Sorry I'm starting to program on android and I don't know how to add the library to my project. The IDE says me that "compile" is obsolete when I add the dependency. I should use implementation but when I use it, it gives me this error:

ERROR: Failed to resolve: agency.tango
Affected Modules: app

these are my dependencies:

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    **implementation 'agency.tango.android:material-intro-screen:{latest_release}'**
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

Sorry, I'm starting to program on Android and I do not know how to add the library to my project. The IDE says that "compile" is obsolete when I add dependency. I should use the implementation, but when I use it, I get this error:

ERROR: Error in resolving: agency.tango
Modules affected: application

These are my dependencies:

dependencies {
implementation fileTree (dir: 'libs', includes: ['* .jar'])
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support.constraint: design-restriction: 1.1.3'
** implementation 'agency.tango.android:material-intro-screen:{latest_release}'**
Implementation 'junit: junit: 4.12'
androidTestImplementation 'com.android.support.test: runner: 1.0.2'
androidTestImplementation 'com.android.support.test.espresso: espresso-core: 3.0.2'
}

Do I have to add something else?

**Comment by rulogas** [comment]
ok I think was for {lates release}, I didn't see it sorry. But now I have problem with versions.

**Comment by rulogas** [comment]
Does it work for android 8 or 9?

**Comment by bezmian** [comment]
Yes
