### ISSUE TITLE
This intro screen every time I launch the app.

### ISSUE THREAD

**Issue by NarzaryU** [TangoAgency/material-intro-screen#183]
Hi @DreierF
 I used your library but the intro screen launch every time at app start. It would be helpful if you can show me how to show it only once.

**Comment by thebentiq** [comment]
Try to use SharedPreferences as a temporary workaround. Initially set preference to false/0 and after intro has been used it would change the value itself to true/1. When app opens, it detects that value is now true and intro would not show up.
