### ISSUE TITLE
Next button does not appear if translation is set

### ISSUE THREAD

**Issue by ionutandone** [TangoAgency/material-intro-screen#24]
Even the sample doesn't show the next button. The button transitions into view after first slide.

The button appears if you remove:
```java
getNextButtonTranslationWrapper()
               .setEnterTranslation(new IViewTranslation() {
                    @Override
                    public void translate(View view, @FloatRange(from = 0, to = 1.0) float percentage) {
                        view.setAlpha(percentage);
                    }
                });
```

Android version 4.3  (API 18) running on Samsung Galaxy Nexus.

**Comment by bezmian** [comment]
Please provide some video with issue.

**Comment by ionutandone** [comment]
![device-2016-10-10-212028](https://cloud.githubusercontent.com/assets/8360692/19248325/944c0e88-8f2f-11e6-85ae-ca7c36f98426.png)
![device-2016-10-10-212049](https://cloud.githubusercontent.com/assets/8360692/19248324/944be11a-8f2f-11e6-81c4-f64b8e232155.png)
![device-2016-10-10-212102](https://cloud.githubusercontent.com/assets/8360692/19248326/944eb1c4-8f2f-11e6-98c8-59796a3f9dce.png)

**Comment by bezmian** [comment]
@radzio https://github.com/TangoAgency/material-intro-screen/pull/26
@ionutandone I have realised, that I have created an example which can be misunderstood by other developers. I have updated the example in above PR, but the feature:
```java
getNextButtonTranslationWrapper()
               .setEnterTranslation(...)
```
will be still available as some developers might want to use it.
