### ISSUE TITLE
canMoveFurther on last slide: swipe still working

### ISSUE THREAD

**Issue by Scrounger** [TangoAgency/material-intro-screen#32]
@radzio 
If have a customSlide as lastslide, excatly like your example:
https://github.com/TangoAgency/material-intro-screen/blob/master/app/src/main/java/agency/tango/materialintro/CustomSlide.java

In some cases it is possible to swipe it away without recognizing the canMoveFurther() condition (in this case, accepting the terms of use)

**Comment by bezmian** [comment]
Resolved in https://github.com/TangoAgency/material-intro-screen/issues/19. Please use 0.0.4 version

**Comment by Scrounger** [comment]
@bezmian 
I use and tested it with v0.0.4 on API 23.
It happens if you swipe fast throug all slides.
It only works if you wait ~1s on the last slide.

**Comment by bezmian** [comment]
@Scrounger Please record gif with issue. I will investigate as soon as possible

**Comment by Scrounger** [comment]
@bezmian 
![Uploading bug_sliding.gif…]()

**Comment by bezmian** [comment]
@Scrounger What is your testing device?

**Comment by Scrounger** [comment]
@bezmian 
Testing device: Emulator Nexus 5 (API 23) and Nexus 5 (API)
Sorry, sharing the project code is not possible.

**Comment by bezmian** [comment]
@radzio https://github.com/TangoAgency/material-intro-screen/pull/34

**Comment by Scrounger** [comment]
Issue has fixed, thanks!

**Comment by shashipyadav** [comment]
this Issue has  not fixed
same issue found

**Comment by radzio** [comment]
@shashipyadav  pls provide steps to reproduce.

Thanks!

**Comment by shashipyadav** [comment]
Steps are:
1. Create a custom slide which is same as the image given in above example (GIF)
2. Add this as the end slide.
3. Once deployed on Mobile, try to swipe fast.

Behaviour: Sometimes validation doesnt work and it is allowing to finish the Into.[Bug]

**Comment by shashipyadav** [comment]
Steps are:

Create a custom slide which is same as the image given in above example (GIF)
Add this as the end slide.
Once deployed on Mobile, try to swipe fast.
Behaviour: Sometimes validation doesnt work and it is allowing to finish the Into.[Bug]

**Comment by shashipyadav** [comment]
plz solve my problem

**Comment by imkh** [comment]
Have the same issue but on the first slide, although I don't think the position is the cause of this problem. But for some reason, the issue stop after a few swipes (see GIF below).

![](https://thumbs.gfycat.com/JealousSatisfiedCockroach-size_restricted.gif)

Another thing I noticed: if you try to go the previous slide, the block is "lifted" and you can manage to pass the slide:

![](https://thumbs.gfycat.com/MemorableFaroffAardvark-size_restricted.gif)

Tested on Pixel XL (Emulator and physical device, API 25) and Nexus 4 (Emulator, API 16).
