### ISSUE TITLE
No support for Android TV / Gamepads

### ISSUE THREAD

**Issue by Fleker** [TangoAgency/material-intro-screen#35]
This doesn't work on an Android TV. From the demo project, I can move left and right to navigate between different views until the "Terms & Conditions". I can't focus on the checkbox and I'm stuck.

**Comment by bezmian** [comment]
@Fleker Great idea! I will add support for that in upcoming library version 0.0.5. Also, I'm sorry but I need to decline your PR as I want to resolve it in another way.

**Comment by bezmian** [comment]
@radzio https://github.com/TangoAgency/material-intro-screen/pull/38
