### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by OssamaTamraoui** [TangoAgency/material-intro-screen#37]
Gradle failed to resolve compile 'agency.tango.android:material-intro-screen:{latest_release}
And i had to search for the latest release manually which is 0.0.4 and add it manually 

compile 'agency.tango.android:material-intro-screen:0.0.4

**Comment by nickyrabit** [comment]
did you get to solve the issue?

**Comment by radzio** [comment]
Make sure that you have jcenter() repository in your build.gradle file.

```
repositories {
        jcenter()
}
```

**Comment by das-abhilash** [comment]
No, I have 
repositories {
        jcenter()
}
but it's can't resolve.

**Comment by radzio** [comment]
There is no problem when resolving 

`compile 'agency.tango.android:material-intro-screen:0.0.4'

You will never be able to resolve

`compile 'agency.tango.android:material-intro-screen:{latest_release}`

{latest_release} in a placeholder for proper library version ;-)
