### ISSUE TITLE
ParallaxFrameLayout example

### ISSUE THREAD

**Issue by am2222** [TangoAgency/material-intro-screen#47]
Hi,
I have set up ParallaxFrameLayout but nothing changed in my slide. Can some one please share me some examples of how it works? or even some videos which shows diffrent between parallax slides and simple one?
thanks very much

**Comment by bezmian** [comment]
https://github.com/TangoAgency/material-intro-screen/raw/master/images/simple_slide.gif
On this gif, every item such as TextView or ImageView while sliding are moving asynchronously. Without parallax, they will move at the same speed. Remember to set parallaxFactor in your layout. Without that, nothing will happen.

**Comment by am2222** [comment]
@bezmian  wow,Thanks for your help.
