### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by gokhanaliccii** [TangoAgency/material-intro-screen#49]
When i added neededPermission like 
`.neededPermissions(new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.INTERNET})`.After run my app on test device (5.1)   I saw grant button on screen but problem is after clicked grant button nothing happening. 

Inside "nextButtonBehaviour()" function you check hasPermissionToGrant but if you need permission not trigger permission request and not checking really need permission  like "android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M"  only set permissionNotGrantedClickListener so user click to grant see showPermissionsNotGrantedError() text

**Comment by bezmian** [comment]
@radzio https://github.com/TangoAgency/material-intro-screen/pull/78, but please first merge https://github.com/TangoAgency/material-intro-screen/pull/75

**Comment by radzio** [comment]
@gokhanaliccii  Maybe we should hide permission buttons on SDK < M? What do you think?

**Comment by masooddalman** [comment]
simply just Override it like this

in your String.xml file write this lines:

```
<string name="grant_permissions">YOUR TEXT</string>
    <string name="please_grant_permissions">YOUR TEXT</string>
    <string name="impassable_slide">YOUR TEXT</string>
```
