### ISSUE TITLE
Intro Screen also known OnBoarding Screen

### ISSUE THREAD

**Issue by webserveis** [TangoAgency/material-intro-screen#5]
Intro Screen also known OnBoarding Screen

https://www.google.es/search?q=onboarding+screen&safe=off&biw=1440&bih=770&source=lnms&tbm=isch&sa=X&sqi=2&ved=0ahUKEwi7zanf2J3PAhUCLhoKHWuVDU4Q_AUIBigB

In materialUp: https://material.uplabs.com/search?q=onboarding

**Comment by radzio** [comment]
Closed because it was SPAM.

**Comment by radzio** [comment]
This issue is irrelevant = CLOSING.
