### ISSUE TITLE
Performance Issue when adding multiple fragments

### ISSUE THREAD

**Issue by MaxToyberman** [TangoAgency/material-intro-screen#53]
The application doesn't respond when adding multiple fragments. 
this occurs when pressing the next and back button.

**Comment by bezmian** [comment]
Please add more information. What device are you using, also how many fragments have you add?

**Comment by MaxToyberman** [comment]
I have tested this on 2 different devices, the first one is nexus 5 and the second one is Samsung galaxy sm-j500.
I am adding 6 fragments but there is only text in there...
I have tried to run your app from the example ,if i add some simple fragments to it doesn't work.

Thanks

**Comment by bezmian** [comment]
@MaxToyberman Are you sure that it's performance issue? I have tested app on Sony Xperia Z with 8 fragments and it works like a charm. Also please notice that max number of fragments held in memory is 5 (the current one, and two for both sides).

**Comment by MaxToyberman** [comment]
@bezmian Did you check it on a real device or an emulator ?
because it works ok on GenyMotion.
on a real device even when i run your example and i copy paste your slides it is stuck.
 
maybe i can record my screen and show you this.

**Comment by bezmian** [comment]
I tested it on real device, Genymotion and Android studio emulator as well.

**Comment by MaxToyberman** [comment]
@bezmian I have found the problem.... this was caused by instantiating SharedPreferences in the fragment
