### ISSUE TITLE
Slides displayed are semi-transparent

### ISSUE THREAD

**Issue by CeJienAJPC** [TangoAgency/material-intro-screen#54]
I tried implementing both _Simple Slide_ and even _Custom Slide_. I both cases, the displayed Slide appears semi-transparent. Here is the image for Reference.

![screenshot_1481084056](https://cloud.githubusercontent.com/assets/15603039/20954505/f807c976-bc61-11e6-874d-673d12ab67b2.png)

There is nothing different from your Code

```
public class TourActivity extends MaterialIntroActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        enableLastSlideAlphaExitTransition(true);

        addSlide(new TourOneFragment());
    }

    @Override
    public void onFinish() {
        super.onFinish();
        startActivity(new Intent(this, MainActivity.class));
    }
}
```

Am I missing something?

Regards

**Comment by bezmian** [comment]
It will be fixed in future releases. Right now please add another fragment and the issue will be gone.

**Comment by bezmian** [comment]
I have a question, do you use 0.0.5 version of the library?

**Comment by CeJienAJPC** [comment]
@bezmian sorry for the late reply. My City was blacked out for the past 10 days (no power, no internet) due to recent Hurricane. Hence no way to reply you. To answer your question, yes I am using the 0.0.5 version of the library.

**Comment by Mauker1** [comment]
Also got this problem. For now the workaround is to add a stub Fragment?

**Comment by itamaradin15** [comment]
You tried changing the background color?

**Comment by nathan-osman** [comment]
I'm seeing this too, even with a background color explicitly set using `SlideFragmentBuilder().backgroundColor()`.

It is also worth noting that this only happens when I have a single slide. For two or more slides, it works fine.

**Comment by bezmian** [comment]
Fixed in https://github.com/TangoAgency/material-intro-screen/pull/72/files
