### ISSUE TITLE
Issue with marshamallow

### ISSUE THREAD

**Issue by sagar091** [TangoAgency/material-intro-screen#56]
I used only one slide and when slide right, MainActivity must open. But in case of marshmallow OS, when I slide right partially, MainActivity cannot visible.. And when I slide right totally then it is visible on screen. Except marshmallow, work completely. Any suggestion or any trick for Marshmallow OS..??

**Comment by bezmian** [comment]
That's Marshmallow bug. Can't do anything about that :(
