### ISSUE TITLE
Title String Error

### ISSUE THREAD

**Issue by laylaykom** [TangoAgency/material-intro-screen#58]
Hey, I'm Furkan. I get an error when I put a string in " .title " There is error; 

> description (java.lang.String) in SlideFragmentBuilder cannot be applied to (int)

**Comment by radzio** [comment]
@laylaykom  you need to pass String resource, not String instance. We are aware of this and we will provide more error-prone API in one of the next versions.

**Comment by laylaykom** [comment]
Okay, I'm waiting 😊

**Comment by bezmian** [comment]
https://github.com/TangoAgency/material-intro-screen/pull/71 @radzio

**Comment by radzio** [comment]
Fixed in https://github.com/TangoAgency/material-intro-screen/pull/71
