### ISSUE TITLE
Error message doesn't display on failed swipe

### ISSUE THREAD

**Issue by coreywoodfield** [TangoAgency/material-intro-screen#61]
I think this library is great, but there is one thing that bugs me. 

I made a custom fragment with some checkboxes, and I have overridden canMoveFurther and cantMoveFurtherErrorMessage. When the condition for canMoveFurther is not met, both pushing the button and trying to swipe to the next fragment fail (as is expected). However, the error message is only displayed if they push the button. If I try to swipe to the next fragment, nothing happens (I don't get the next fragment and the error message doesn't display). Are there plans to display the error message on swipe as well? That seems like it would be the desired behavior.

I'm not sure if the same happens on non-custom fragments, as I haven't tested, but it seems like it would.

**Comment by bezmian** [comment]
@radzio https://github.com/TangoAgency/material-intro-screen/pull/77

**Comment by Mauker1** [comment]
+1

**Comment by radzio** [comment]
Fixed in #77
