### ISSUE TITLE
"animationDuration" styleable conflict

### ISSUE THREAD

**Issue by volvciklum** [TangoAgency/material-intro-screen#63]
"animationDuration" styleable may conflict with another one from different library. And it does in my case. Propose to rename all styleables to include some unique prefix for ex. "mis".

**Comment by bezmian** [comment]
https://github.com/TangoAgency/material-intro-screen/pull/73 @radzio

**Comment by radzio** [comment]
Fixed in https://github.com/TangoAgency/material-intro-screen/pull/73
