### ISSUE TITLE
Rotation of final slide causes transparent background

### ISSUE THREAD

**Issue by achuinard** [TangoAgency/material-intro-screen#64]
If you rotate the activity when on the final fragment, the background becomes totally transparent and is only fixed when scrolling back a slide.

**Comment by bezmian** [comment]
https://github.com/TangoAgency/material-intro-screen/pull/72/files @radzio

**Comment by broakenmedia** [comment]
Any clues on when 0.0.6 will make it to release? Last slide rotation for me causes the forward and backward buttons to go white and the indicators to go red. Fixed by going back a slide. Not viable for a public app currently!

**Comment by achuinard** [comment]
Waiting on 0.0.6 myself

**Comment by achuinard** [comment]
@radzio @bezmian when do you plan to release 0.0.6?
