### ISSUE TITLE
GRadle sync not working while adding to module level gradle.

### ISSUE THREAD

**Issue by kbathwal** [TangoAgency/material-intro-screen#94]
I am adding     the below line to Module level Build.gradle
**compile 'agency.tango.android:material-intro-screen{latest_release}'**

Upon sync of gradle its showing an error-

**Error:Failed to resolve: agency.tango.android:material-intro-screen{latest_release}:**

> Please help. Its urgent. What to put in place of {latest_release}

**Comment by radzio** [comment]
You have to replace **{latest_release}** with latest library version, currently it is **0.0.5**

![screenshot](https://cloud.githubusercontent.com/assets/469111/24092909/9288a840-0d51-11e7-81f4-75c872dc7b3a.png)
