### ISSUE TITLE
Colors go crazy on last slide when device is rotated

### ISSUE THREAD

**Issue by GaryCuevas** [TangoAgency/material-intro-screen#95]
Rotating the Android device when the last slide of a series is displayed results in the colors going crazy. Easily reproduced with the supplied sample app.

(This may be related to bug #45 (Single slide intro calculates wrong background color).

**Comment by GaryCuevas** [comment]
I set some breakpoints in the code to see what happens when onCreate() is called on screen rotation when that last slide is showing. I saw some code for setting up the slide colors that was explicitly not called in this situation. I tried to work around the problem with various fixes but I ran into trouble.

**Comment by bezmian** [comment]
You mean something like this: https://github.com/TangoAgency/material-intro-screen/issues/64 ?

**Comment by GaryCuevas** [comment]
Yes, exactly that. Sorry I didn't see it was already filed.

**Comment by GaryCuevas** [comment]
Thanks for pointing this out. I'll have a chance to incorporate the fix when I get back to the office on Wednesday. Really appreciate it!

**Comment by GaryCuevas** [comment]
Integrated and it works like a dream! Thanks so much.

Good luck with case #96 :)
