### ISSUE TITLE
Gradle sync throwing error

### ISSUE THREAD

**Issue by srujanb** [TangoAgency/material-intro-screen#99]
I tried syncing with the 0.0.5 version and the gradle itself is giving the error:

    C:\Users\Srujan\AndroidStudioProjects\MsImpLinksV2.1\app\build\intermediates\res\merged\debug\values-v11\values-v11.xml
    Error:(73, 54) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').
    Error:(73, 54) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').
    Error:Execution failed for task ':app:processDebugResources'.
    com.android.ide.common.process.ProcessException: Failed to execute aapt
    Information:BUILD FAILED

**Comment by radzio** [comment]
I'm not convinced that it is our fault. Are you using gradle dependency like this:
`compile 'agency.tango.android:material-intro-screen:0.0.5'`

**Comment by srujanb** [comment]
@radzio  Yes I am!

**Comment by radzio** [comment]
We are not using `abc_ic_ab_back_mtrl_am_alpha` anywhere in our code. It is possible that you are using another version of the support library ( Material Intro Screen uses `25.0.1`, we will upgrade it in the upcoming 0.0.6 version).

**Comment by srujanb** [comment]
I am using 23.4.0 support library. Could that be the reason? I am really not looking to change it to 25.0.1 which is throwing another exception in my almost-finished application. Or May be.. let me give it a try with 25.0.1

**Comment by radzio** [comment]
As I thought - it is our issue. Closing this issue and good luck :-)
